// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	LoginPostOperation     OperationName = "LoginPost"
	RefreshPostOperation   OperationName = "RefreshPost"
	SignupPostOperation    OperationName = "SignupPost"
	UsersGetOperation      OperationName = "UsersGet"
	UsersIDDeleteOperation OperationName = "UsersIDDelete"
	UsersIDGetOperation    OperationName = "UsersIDGet"
	UsersIDPatchOperation  OperationName = "UsersIDPatch"
)
