// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Represents error object.
// Ref: #/components/schemas/Error
type Error struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int64 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int64) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/LoginRequest
type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// GetUsername returns the value of Username.
func (s *LoginRequest) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *LoginRequest) GetPassword() string {
	return s.Password
}

// SetUsername sets the value of Username.
func (s *LoginRequest) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *LoginRequest) SetPassword(val string) {
	s.Password = val
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type RefreshPostReq struct {
	RefreshToken OptString `json:"refresh_token"`
}

// GetRefreshToken returns the value of RefreshToken.
func (s *RefreshPostReq) GetRefreshToken() OptString {
	return s.RefreshToken
}

// SetRefreshToken sets the value of RefreshToken.
func (s *RefreshPostReq) SetRefreshToken(val OptString) {
	s.RefreshToken = val
}

// Ref: #/components/schemas/SignupRequest
type SignupRequest struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetUsername returns the value of Username.
func (s *SignupRequest) GetUsername() string {
	return s.Username
}

// GetEmail returns the value of Email.
func (s *SignupRequest) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *SignupRequest) GetPassword() string {
	return s.Password
}

// SetUsername sets the value of Username.
func (s *SignupRequest) SetUsername(val string) {
	s.Username = val
}

// SetEmail sets the value of Email.
func (s *SignupRequest) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *SignupRequest) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/TokenResponse
type TokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// GetAccessToken returns the value of AccessToken.
func (s *TokenResponse) GetAccessToken() string {
	return s.AccessToken
}

// GetRefreshToken returns the value of RefreshToken.
func (s *TokenResponse) GetRefreshToken() string {
	return s.RefreshToken
}

// SetAccessToken sets the value of AccessToken.
func (s *TokenResponse) SetAccessToken(val string) {
	s.AccessToken = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *TokenResponse) SetRefreshToken(val string) {
	s.RefreshToken = val
}

// Ref: #/components/schemas/User
type User struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Role     string `json:"role"`
}

// GetID returns the value of ID.
func (s *User) GetID() int {
	return s.ID
}

// GetUsername returns the value of Username.
func (s *User) GetUsername() string {
	return s.Username
}

// GetEmail returns the value of Email.
func (s *User) GetEmail() string {
	return s.Email
}

// GetRole returns the value of Role.
func (s *User) GetRole() string {
	return s.Role
}

// SetID sets the value of ID.
func (s *User) SetID(val int) {
	s.ID = val
}

// SetUsername sets the value of Username.
func (s *User) SetUsername(val string) {
	s.Username = val
}

// SetEmail sets the value of Email.
func (s *User) SetEmail(val string) {
	s.Email = val
}

// SetRole sets the value of Role.
func (s *User) SetRole(val string) {
	s.Role = val
}

// Ref: #/components/schemas/UserUpdate
type UserUpdate struct {
	Username OptString `json:"username"`
	Email    OptString `json:"email"`
	Role     OptString `json:"role"`
}

// GetUsername returns the value of Username.
func (s *UserUpdate) GetUsername() OptString {
	return s.Username
}

// GetEmail returns the value of Email.
func (s *UserUpdate) GetEmail() OptString {
	return s.Email
}

// GetRole returns the value of Role.
func (s *UserUpdate) GetRole() OptString {
	return s.Role
}

// SetUsername sets the value of Username.
func (s *UserUpdate) SetUsername(val OptString) {
	s.Username = val
}

// SetEmail sets the value of Email.
func (s *UserUpdate) SetEmail(val OptString) {
	s.Email = val
}

// SetRole sets the value of Role.
func (s *UserUpdate) SetRole(val OptString) {
	s.Role = val
}

// UsersIDDeleteNoContent is response for UsersIDDelete operation.
type UsersIDDeleteNoContent struct{}
